name: "Setup npm"
description: "Install Node.js and npm dependencies"
runs:
  using: "composite"
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm

    - name: Install dependencies
      shell: bash
      run: npm ci
